# Writes the header that carries this build's git description, for
# src/core/Version.cpp. Run in script mode, at configure time once and then on
# every build, so the string names the commit that was actually built rather
# than the one that happened to be checked out when cmake last ran:
#
#     cmake -DSOURCE_DIR=<source> -DOUTPUT=<header> -P cmake/GitVersion.cmake
#
# There is deliberately no failure path. A source tree with no git history is a
# normal way to build this -- a release tarball, an unpacked copy, a machine
# with no git installed -- and all of those leave the description empty, which
# is what Version.cpp treats as "nothing to say".
foreach(argument SOURCE_DIR OUTPUT)
    if(NOT DEFINED ${argument})
        message(FATAL_ERROR "GitVersion.cmake requires -D${argument}=...")
    endif()
endforeach()

set(describe "")
# The .git entry must be this tree's own: a directory in a clone, a file in a
# worktree or submodule. Testing for it, rather than asking git whether the
# directory is inside a work tree, is what keeps an unpacked copy that happens
# to sit inside some unrelated repository from reporting that repository's
# commits as its own.
if(EXISTS "${SOURCE_DIR}/.git")
    find_package(Git QUIET)
    if(Git_FOUND)
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" describe --tags --dirty --always
            WORKING_DIRECTORY "${SOURCE_DIR}"
            OUTPUT_VARIABLE describe
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
            RESULT_VARIABLE status)
        if(NOT status EQUAL 0)
            # A repository with no commits yet, or any other refusal.
            set(describe "")
        endif()
    endif()
endif()

set(content
    "#pragma once\n"
    "\n"
    "// Generated by cmake/GitVersion.cmake. Do not edit, do not commit.\n"
    "#define AMREXPLORER_GIT_DESCRIBE \"${describe}\"\n")
string(JOIN "" content ${content})

# Only when it changed: an unconditional write would give the header a new
# timestamp on every build and recompile Version.cpp for nothing.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
