# Writes the header that carries this build's git description, for
# src/core/Version.cpp. Run in script mode, at configure time once and then on
# every build, so the string names the commit that was actually built rather
# than the one that happened to be checked out when cmake last ran:
#
#     cmake -DSOURCE_DIR=<source> -DOUTPUT=<header> -P cmake/GitVersion.cmake
#
# There is deliberately no failure path. A source tree with no git history is a
# normal way to build this -- a release tarball, an unpacked copy, a machine
# with no git installed -- and all of those leave the description empty, which
# is what Version.cpp treats as "nothing to say".
foreach(argument SOURCE_DIR OUTPUT)
    if(NOT DEFINED ${argument})
        message(FATAL_ERROR "GitVersion.cmake requires -D${argument}=...")
    endif()
endforeach()

set(describe "")
# The .git entry must be this tree's own: a directory in a clone, a file in a
# worktree or submodule. Testing for it, rather than asking git whether the
# directory is inside a work tree, is what keeps an unpacked copy that happens
# to sit inside some unrelated repository from reporting that repository's
# commits as its own.
if(EXISTS "${SOURCE_DIR}/.git")
    find_package(Git QUIET)
    if(Git_FOUND)
        # Through `cmake -E env`, to drop the GIT_* variables a build launched
        # from a hook or `git rebase --exec` inherits: GIT_DIR and
        # GIT_WORK_TREE override the working directory, and GIT_INDEX_FILE
        # sends --dirty to an unrelated index, which is exactly the "describes
        # some other repository" answer the .git check above rules out.
        # --no-optional-locks so --dirty does not write .git/index.lock: two
        # builds over one checkout would otherwise race, and the loser drops
        # the description.
        execute_process(
            COMMAND "${CMAKE_COMMAND}" -E env
                --unset=GIT_DIR --unset=GIT_WORK_TREE --unset=GIT_INDEX_FILE
                "${GIT_EXECUTABLE}" --no-optional-locks
                describe --tags --dirty --always
            WORKING_DIRECTORY "${SOURCE_DIR}"
            OUTPUT_VARIABLE describe
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
            RESULT_VARIABLE status)
        if(NOT status EQUAL 0)
            # A repository with no commits yet, or any other refusal.
            set(describe "")
        endif()
    endif()
endif()

# The description ends up inside a C++ string literal, and a tag name is not a
# safe token: git rejects spaces, control characters and a handful of glob
# characters in a ref, but permits `"`, which would end the literal early and
# leave a header that does not compile. Escape rather than trust it. Backslash
# first, so escaping the quote does not then escape its own backslash -- git
# rejects backslashes in refs today, which is not a reason for this to be the
# one line that breaks if that ever changes.
string(REPLACE "\\" "\\\\" describe_literal "${describe}")
string(REPLACE "\"" "\\\"" describe_literal "${describe_literal}")

# One string, deliberately, and never expanded as a list: a `;` in the
# description is a list separator to CMake, and joining the elements again
# would silently drop it -- a version that quietly disagrees with git is worse
# than one that fails to build.
set(content "#pragma once\n\n")
string(APPEND content
    "// Generated by cmake/GitVersion.cmake. Do not edit, do not commit.\n")
string(APPEND content
    "#define AMREXPLORER_GIT_DESCRIBE \"${describe_literal}\"\n")

# Only when it changed: an unconditional write would give the header a new
# timestamp on every build and recompile Version.cpp for nothing.
set(existing "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
